# Funções para criar arrays
***

O Numpy também fornece funções para criação de arrays

***

In [1]:
# Importa o modulo numpy
import numpy

***

In [2]:
# Vamos criar um array com um range()
array = numpy.arange(0, 10, 2)
print(array)

[0 2 4 6 8]


***

In [3]:
# Criar um array de zeros
array = numpy.zeros(5)
print(array)

[ 0.  0.  0.  0.  0.]


***

In [4]:
# Criar uma matriz de zeros
matrix = numpy.zeros((3, 2))
print(matrix)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


***

In [5]:
# Criar um array de uns
array = numpy.ones(5)
print(array)
print(array * 5)

[ 1.  1.  1.  1.  1.]
[ 5.  5.  5.  5.  5.]


***

In [6]:
# Criar uma matriz de uns
matrix = numpy.ones((3, 3))
print(matrix)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


***

In [7]:
# Criando um array com 5 valores linearmente espaçados entre 0 e 9
array = numpy.linspace(0, 5, 10)
print(array)

[ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]


***

In [8]:
# Matriz identidade
array = numpy.eye(4)
print(array)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


***

In [9]:
# Criar números randomicos no array ou matriz de 0 a 1
print(numpy.random.rand(5), "\n")
print(numpy.random.rand(5, 5))

[ 0.30940357  0.39256322  0.34707919  0.75614227  0.04547841] 

[[ 0.56954203  0.35769924  0.4459637   0.43149576  0.38163096]
 [ 0.83789798  0.78902605  0.87288494  0.46719857  0.81956475]
 [ 0.83338129  0.4945483   0.01659554  0.98462074  0.46653605]
 [ 0.52257118  0.02302133  0.77026604  0.0850156   0.44348254]
 [ 0.68484962  0.32881578  0.3030906   0.57257398  0.53419938]]


***

In [10]:
# Pega um número aleatorio inteiros entre um valor e outro(exclusivo)
# Podemos passar a quantidade como terceiro argumento.
print(numpy.random.randint(1, 100))
print(numpy.random.randint(1, 100, 5))

65
[36 19 81 45 40]


***

In [11]:
# Vamos pegar um array e modificar o shape dele
array = numpy.array([1, 5, 7, 2, 7, 8, 22, 67])
print(array)

[ 1  5  7  2  7  8 22 67]


In [12]:
# Para dar certo o reshape número de colunar veze o número de linhas
# tem que dar o total de elementos do array: 2*3 = 6
array = array.reshape((2,4))
print(array)

[[ 1  5  7  2]
 [ 7  8 22 67]]


***

In [13]:
# Exemplo um pouco mais complexo
print(numpy.arange(1, 101).reshape(10, 10) / 100)

[[ 0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.1 ]
 [ 0.11  0.12  0.13  0.14  0.15  0.16  0.17  0.18  0.19  0.2 ]
 [ 0.21  0.22  0.23  0.24  0.25  0.26  0.27  0.28  0.29  0.3 ]
 [ 0.31  0.32  0.33  0.34  0.35  0.36  0.37  0.38  0.39  0.4 ]
 [ 0.41  0.42  0.43  0.44  0.45  0.46  0.47  0.48  0.49  0.5 ]
 [ 0.51  0.52  0.53  0.54  0.55  0.56  0.57  0.58  0.59  0.6 ]
 [ 0.61  0.62  0.63  0.64  0.65  0.66  0.67  0.68  0.69  0.7 ]
 [ 0.71  0.72  0.73  0.74  0.75  0.76  0.77  0.78  0.79  0.8 ]
 [ 0.81  0.82  0.83  0.84  0.85  0.86  0.87  0.88  0.89  0.9 ]
 [ 0.91  0.92  0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.  ]]


In [14]:
print(numpy.linspace(0.01, 1, 100).reshape(10, 10))

[[ 0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.1 ]
 [ 0.11  0.12  0.13  0.14  0.15  0.16  0.17  0.18  0.19  0.2 ]
 [ 0.21  0.22  0.23  0.24  0.25  0.26  0.27  0.28  0.29  0.3 ]
 [ 0.31  0.32  0.33  0.34  0.35  0.36  0.37  0.38  0.39  0.4 ]
 [ 0.41  0.42  0.43  0.44  0.45  0.46  0.47  0.48  0.49  0.5 ]
 [ 0.51  0.52  0.53  0.54  0.55  0.56  0.57  0.58  0.59  0.6 ]
 [ 0.61  0.62  0.63  0.64  0.65  0.66  0.67  0.68  0.69  0.7 ]
 [ 0.71  0.72  0.73  0.74  0.75  0.76  0.77  0.78  0.79  0.8 ]
 [ 0.81  0.82  0.83  0.84  0.85  0.86  0.87  0.88  0.89  0.9 ]
 [ 0.91  0.92  0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.  ]]
