# Indexing e Selection
***

Selecionar elementos de um array de maneira fácil usando indexação ou seleção condicional

***
### Array
***

In [1]:
# Importar o modulo numpy
import numpy

***

In [2]:
# Criar um array simples
array = numpy.arange(0, 11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


***

In [3]:
# Indexing
print(array[3])
print(array[1:5])

3
[1 2 3 4]


***

In [4]:
# copiar e inserir valores dentro dos arrays por slices
copy = array.copy()
copy[1:5] = 10
print(copy[1:])

[10 10 10 10  5  6  7  8  9 10]


***
### Matriz
***

In [5]:
# Criando um array
matrix = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***

In [6]:
# Acessando elementos da matriz
print(matrix[0][0], matrix[1][1], matrix[2][2])
print(matrix[0, 0], matrix[1, 1], matrix[2, 2])

1 5 9
1 5 9


***

In [7]:
# Acessando linhas da matriz
print(matrix[0], matrix[1], matrix[2])

[1 2 3] [4 5 6] [7 8 9]


***

In [8]:
# Slices em matrizes, pegue as linhas 0 e 1
# e pegue as colunas 1 em diante
print(matrix[:2, 1:])

[[2 3]
 [5 6]]


***
### selection
***

In [9]:
# Criar um array simples
array = numpy.arange(0, 11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


***

In [10]:
# Vamos verificar quais valores são maiores que 5 no array
boolean_array = array > 5
print(boolean_array)

[False False False False False False  True  True  True  True  True]


***

In [11]:
# Vamos criar um array só com os valores maiores que 5
# ele verifica e insere só os valores que estão na posição True
print(array[boolean_array])

[ 6  7  8  9 10]


***

In [12]:
# Com isso podemos fazer codições para recuperar elementos do array
print(array[array > 5])
print(array[array % 2 == 0])

[ 6  7  8  9 10]
[ 0  2  4  6  8 10]


***
### Iteração
***

In [13]:
# Declarando um array bidimensional
matrix = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


***

In [14]:
# Iterando sobre os elementos de um array
for row in matrix:
    print(row)
    for element in row:
        print(element)

[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8
