# Operações com arrays
***

É possível realizar operações elemento a elemento com arrays. As operações elemento a elemento são: soma (+), subtração (-), multiplicação (*) e divisão (/). Para realizar este tipo de operação, é preciso que os arrays tenham o mesmo tamanho em todas as dimensões ou um deles tenha tamanho 1 na dimensão.

Operações de arrays:

* **produto interno**: ...

* **produto externo**: ...

* **produto escalar**: ...

* **matriz transposta**: ...

* **matriz inversa**: ...

Solução de sistema linear:

...

***
### Operações básicas
***

In [1]:
# importa o modulo
import numpy

***

In [2]:
# Declarando os dois arrays
A = numpy.array([1, 2, 3, 4])
B = numpy.array([2, 3, 5, 6])
print(A)
print(B)

[1 2 3 4]
[2 3 5 6]


***

In [3]:
# Soma entre os arrays A e B
print(A + B)
print(A + 2)

[ 3  5  8 10]
[3 4 5 6]


***

In [4]:
# Subtração entre os arrays A e B
print(A - B)
print(A - 2)

[-1 -1 -2 -2]
[-1  0  1  2]


***

In [5]:
# Multiplicação entre os arrays A e B
print(A * B)
print(A * 2)

[ 2  6 15 24]
[2 4 6 8]


***

In [6]:
# Divisão entre os arrays A e B
print(A / B)
print(A / 2)

[ 0.5         0.66666667  0.6         0.66666667]
[ 0.5  1.   1.5  2. ]


***

In [7]:
# Potencia entre arrays
print(A ** B)
print(A ** 2)

[   1    8  243 4096]
[ 1  4  9 16]


***

In [8]:
# Outras funções que podem ser aplicadas
print(numpy.sqrt(A))
print(numpy.exp(A))
print(numpy.sin(A))
print(numpy.log(A))

[ 1.          1.41421356  1.73205081  2.        ]
[  2.71828183   7.3890561   20.08553692  54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.          0.69314718  1.09861229  1.38629436]


***
### Operações vetoriais e matriciais
***

O Numpy também pode ser utilizado para realizar operações vetoriais e operações matriciais em arrays. Entre elas, estão: produto interno, produto externo, produto escalar, matriz transposta e matriz inversa.

In [9]:
# Declarando dois vetores (arrays unidimensionais)
A = numpy.array([1, 2, 3, 4])
B = numpy.array([2, 3, 5, 6])
print(A)
print(B)
print("Soma de todos os elementos de A:", sum(A))
print("Desvio padrão de A:", A.std())

[1 2 3 4]
[2 3 5 6]
Soma de todos os elementos de A: 10
Desvio padrão de A: 1.11803398875


***

In [10]:
# Produto interno
C = numpy.inner(A, B)
print(C)

47


***

In [11]:
# Produto externo
C = numpy.outer(A, B)
print(C)

[[ 2  3  5  6]
 [ 4  6 10 12]
 [ 6  9 15 18]
 [ 8 12 20 24]]


***

In [12]:
# Declarando duas matrizes (arrays bidimensionais)
A = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]])
B = numpy.array([[2, 3, 5, 6], [4, 1, 9, 0]])
print(A, "\n")
print(B)

[[1 2 3 4]
 [5 6 7 8]] 

[[2 3 5 6]
 [4 1 9 0]]


***

In [13]:
# Matriz Transposta
C = A.T
print(C)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


***

In [14]:
# Produto escalar
C = numpy.dot(A, B.T)
print(C)

[[ 47  33]
 [111  89]]


***

In [15]:
# Matriz inversa
A = numpy.arange(4).reshape((2,2))
C = numpy.linalg.inv(A)
print(C)
print("Soma de todas as colunas de C:", C.sum(axis=0))

[[-1.5  0.5]
 [ 1.   0. ]]
Soma de todas as colunas de C: [-0.5  0.5]


***
### Funções Ax = b
***

O Numpy conta com a função solve() para resolver problemas do tipo $Ax = b$. A função funciona da seguinte forma:

In [16]:
# Declarando A e b
A = numpy.array([[1, 2, 3], [9, 4, 2], [6, 0, 1]])
b = numpy.ones((3, 1))
print(A, "\n")
print(b)

[[1 2 3]
 [9 4 2]
 [6 0 1]] 

[[ 1.]
 [ 1.]
 [ 1.]]


***

In [17]:
# Encontrando a solução do sistema linear
x = numpy.linalg.solve(A, b)
print(x)

[[ 0.09677419]
 [-0.17741935]
 [ 0.41935484]]
