# Modulo Numpy
***

Numpy (http://www.numpy.org/) é um módulo fundamental para trabalhar com a computação científica em Python. Este módulo fornece um array multidimensional e diversas ferramentas para trabalhar com estes arrays. Entre as características do módulo Numpy, estão:

* Objeto de array multidimensional;
* Ferramentas de álgebra linear;
* Ferramentas de Transformada de Fourier;
* Ferramentas de geração de números aleatórios.

Para utilizar o módulo Numpy, basta importá-lo. Neste notebook, o Numpy será importado sempre da seguinte maneira:

```py
import numpy
```

Array é uma sequência de elementos do mesmo tipo, formando um conjunto n-dimensional. A forma do array pode ser visualizada através da função shape(), que retorna uma tupla com o tamanho do array em cada dimensão. Os arrays podem ser inicializados com listas e seus elementos podem ser acessados com colchetes.

Um array com uma dimensão tem somente um colchete [] com duas dimensões dois colchetes [[], []] e por ai vai.

Consulta: https://docs.scipy.org/doc/numpy/reference/

Instalação:

```
sudo pip3 install numpy
```

***

# SciPy

O SciPy (https://scipy.org/) é um módulo de algoritmos e ferramentas matemáticas feito para trabalhar com os array do Numpy em Python. Algumas as principais funções do SciPy é trabalhar com:

* Álgebra Linear;
* Estatística;
* Problemas de Otimização;
* Operações com Matrizes Esparsas;
* Processamento de Sinais.

***
### Exemplos
***

In [1]:
# Importa o modulo numpy
import numpy

***

In [2]:
# Criar uma lista
my_list = [1, 2, 3]
print(my_list)

[1, 2, 3]


***

In [3]:
# Vamo através do numpy criar um array unidimensional usando a lista
array = numpy.array(my_list)
print(array)

[1 2 3]


***

In [4]:
# Visualizando a forma do array
print(array.shape)

(3,)


***

In [5]:
# Visualizando o tipo de dados do array
# No caso é um array de interios de 64 bits
print(array.dtype)

int64


***

In [6]:
# Acessando elementos individuais do array
print(array[0], array[1], array[2])

1 2 3


***

In [7]:
# Modificando o valor de um elemento do array
array[1] = 10
print(array)

[ 1 10  3]


***

In [8]:
# Pegar o maior e o menor valor e indice do array
print("Maior valor:", array.max(), "está no indice", array.argmax())
print("Menor valor:", array.min(), "está no indice", array.argmin())

Maior valor: 10 está no indice 1
Menor valor: 1 está no indice 0


***

In [9]:
# Vamo criar uma matriz utilizando várias listas
matrix = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***

In [10]:
# Visualizando a forma da matriz
print(matrix.shape)

(3, 3)


***

In [11]:
# Visualizando o tipo de dados da matriz
# No caso é uma matriz de floats de 64 bits
print(matrix.dtype)

int64


***

In [12]:
# Acessando elementos individuais da matriz
print(matrix[0][0], matrix[1][1], matrix[2][2])
print(matrix[0, 0], matrix[1, 1], matrix[2, 2])

1 5 9
1 5 9
